### PR TITLE
Fix/dont stop selecting nonexist element on synoptic

### PR DESCRIPTION
**Pull request by yamahigashi**
This PR suppresses errors when selecting synoptic elements that does not exist in a scene. I think that this PR may conflict with the previous one( #25 ) when if you try to merge both PR,  soI will close this and send pull request again later  if you need.

### CODE REVIEW

**Comment by miquelcampos** [comment]
Thank you again!

I will check it before Merge.

**Comment by miquelcampos** [comment]
Hello Yamahigashi-san,

I have added the change in "fix to suppress synoptic's updateTabs event while updateModelList" and I believe the other changes are already implemented. So I will close this pull request.

Please don't hesitate to contact me if I miss something.

Thank you,
Miquel

**Comment by yamahigashi** [comment]
Hi @miquelcampos 651f192e1e35723de8edac9e93e169ce1aacd8ff is also necessary ;)

**Comment by miquelcampos** [comment]
@yamahigashi Thank you for the head up. Now is done  :)

**Pull request closed without merging**
