### PR TITLE
[WIP] Add Code Climate

### PR DESCRIPTION
**Pull request by mottosso**
This PR will validate mgear against PEP8, via a cloud service similar to Travis known as Code Climate. What it does is..

1. Look at every Python file
2. Check it against PEP8
3. Produce a report

mgear is currently rated F, with technical debt at 2 years. Meaning Code Climate thinks it'd take 2 years to clean up what it apparently considered a big mess!

Personally I don't think it's that bad, but we have a lot of work ahead of us.

Here's what I need from you that I can't do on my own.

1. Register an account with Code Climate, like you did for Travis
2. Add mgear
3. Set the Default Branch (under Settings) to `develop`. That's assuming this is the branch we're most interested in keeping tabs on.

Here you can see the current report, but beware, it's a little overwhelming!

https://codeclimate.com/github/mottosso/mgear

### CODE REVIEW

**Comment by miquelcampos** [comment]
Hello @mottosso 

Nice! I learning many new resources in 2 days :D 

I have created the account int codeclimate. But I can't change the default branch (at less right now) In the settings area look like is lock.
Do I need to merge this commit before?

And yes! is a little scary the report

**Comment by mottosso** [comment]
Interestingly, when I excluded the `/components` directory, technical debt went from 2 years to 5 months. :)

**Comment by mottosso** [comment]
> Do I need to merge this commit before?

Hmm, I don't think so, but you might be running into the same error I got. Better contact support, like I did. :/ hello@codeclimate.com Just tell them you can't edit the default branch and they'll do it for you.

**Comment by miquelcampos** [comment]
I have send the email to codeclimate support.

**Comment by miquelcampos** [comment]
> Interestingly, when I excluded the /components directory, technical debt went from 2 years to 5 months. :)

The components directory should be the easier to refactore. All the componets follow the same patters and use almost the same functions.  
Maybe is because the _template folder that contains some .ma files. FYI: this files will replace by json files   in the  2.3 release (https://github.com/miquelcampos/mgear/issues/46)
The mocap interface should be in another place, and I should re-do the complete mocap tools in following releases.

**Comment by miquelcampos** [comment]
codeclimate.com is now pointing to develop branch

**Comment by mottosso** [comment]
Ok, we can merge this, and Code Climate will update alongside every new PR.

**Pull request merged**
