### PR TITLE
Restore submodule support on Travis

### PR DESCRIPTION
**Pull request by mottosso**
With https://github.com/miquelcampos/cvwrap/pull/1 merged, we can let Travis clone with submodules. We'll need this for scons to run.

Notice I've added **WIP** to the title so that you know this isn't ready yet. We should wait until Travis works the way we want it to.

### CODE REVIEW

**Comment by miquelcampos** [comment]
Thanks for the [WIP] tagging,

and really nice to see Travis in action.  Clearly this is  very, very useful. But now I have to add/create all the test and Doctests. This is going to be fun!

**Comment by mottosso** [comment]
> But now I have to add/create all the test and Doctests. This is going to be fun!

That's the spirit!

**Comment by mottosso** [comment]
Ok, this works now.

The only remainder is repairing the tests. How are things looking on your end, would you happen to be able to repair these today?

**Comment by miquelcampos** [comment]
Here is 7pm. I will check at home, but provably not too much time left to do any change.

**Comment by mottosso** [comment]
Ok, this is ready to merge!

**Comment by miquelcampos** [comment]
Just add this in top of my "in progress" list. https://github.com/miquelcampos/mgear/projects/2

**Comment by miquelcampos** [comment]
Merge done! :)

**Pull request merged**
