### PR TITLE
Leg ms 2jnt

### PR DESCRIPTION
**Pull request by milesckt**
Component Added: leg_ms_2jnt_01
 - auto up-vector knows foot orientation
 - settingsUI not compatible with Maya 2017, how to fix?

Added connection to leg_ms_2jnt_01 at foot_bk_01
arm_ms_2jnt_01 fk2 offset bug fix

### CODE REVIEW

**Comment by csaez** [comment]
>- settingsUI not compatible with Maya 2017, how to fix?

Maya 2017 moved to Qt5 and there are important changes requiring some extra work (i.e. you should use PySide2 instead of PySide as both versions are not 100% compatible).

There are a few open source projects like [Qt.py](https://github.com/mottosso/Qt.py) aiming to unify the Qt bindings to whatever is available (PySide, PySide2, PyQt4, PyQt5) so the user doesn't have to worry much about it, you could also do some minimal try/except imports in case adding an extra dependency to the project is not desired (I did something similar [here](https://github.com/csaez/quicklauncher/blob/master/quicklauncher.py#L29), maybe it helps as a possible way to solve it).

**Comment by miquelcampos** [comment]
Hi @csaez , 
Thank you for the explanation.

I did a little helper module to solve this. Is not as good as QT.py from Mottosso. But does the work :)

What I do is always compile  the. ui from Maya 2017 and after I edit the  .py manually. Replacing the import with my version:

import mgear.maya.pyqt as gqt
QtGui, QtCore, QtWidgets, wrapInstance = gqt.qt_import()

Also in the retranslateUi function, I replace the default translate with my fake version
i.e:  self.upvRefArrayRemove_pushButton.setText(**gqt.fakeTranslate**("Form", ">>", None, -1))


@milesckt  Plase check other components and Copy/Paste ;)

Thanks,
Miquel

**Comment by milesckt** [comment]
Got  it :)
Thanks @csaez  and @miquelcampos

**Comment by miquelcampos** [comment]
Thank you Miles for the new commit.  The new features looks really cool!

**Comment by milesckt** [comment]
@miquelcampos  Hi,
You're very welcome.
So, the Arm and Leg component is pretty much ported from my XSI version with some little enhancement.
In the toDo list, which is the sleeve controls, would be added later if I have better/new ideas.
Next, will be "shoulder_ms".
Then will take a look and add some stuff to the spline component, like rotation pivot controls (now possible and workable in Maya!) etc...

**Pull request merged**
